FROM node:20-alpine AS ui-builder
WORKDIR /app

COPY ./hub/internal/ui/package*.json ./
RUN npm install

COPY ./hub/internal/ui ./
RUN npm run build

FROM --platform=$BUILDPLATFORM golang:alpine AS builder
WORKDIR /app

COPY --from=ui-builder /app/dist ./internal/site/dist

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN apk add --no-cache unzip ca-certificates && update-ca-certificates

ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /beszel ./internal/cmd/hub

FROM alpine:latest
RUN apk add --no-cache bash
COPY --from=builder /beszel /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
VOLUME ["/beszel_data"]
EXPOSE 8090
ENTRYPOINT [ "/beszel" ]
CMD ["serve", "--http=0.0.0.0:8090"]